# Generated by Django 4.2 on 2024-11-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefeedback',
            name='email_id',
            field=models.EmailField(max_length=100),
        ),
    ]
